/**
 * Lxcore Backend Integration - Configuration Management
 * This module handles configuration file management and command execution
 * The actual system command execution happens on the client via KernelSU APIs
 */

// Configuration paths
export const MODPATH = '/data/adb/modules/Lynx';
export const CONFIG_FILE = `${MODPATH}/script/lib/lynx.conf`;
export const LOG_FILE = '/storage/emulated/0/Lynx/Lynx.log';
export const BUSYBOX_KSU_PATH = '/data/adb/ksu/bin/busybox';
export const BUSYBOX_MAGISK_PATH = '/data/adb/magisk/busybox';

// Type definitions
export interface CommandResult {
  errno: number;
  stdout: string;
  stderr: string;
  success: boolean;
}

export interface SystemMetrics {
  cpu: {
    usage: number;
    cores: number;
    frequency: string[];
    governors: string[];
  };
  gpu: {
    frequency: string;
    load: number;
  };
  ram: {
    total: number;
    available: number;
    used: number;
    percentage: number;
  };
  thermal: {
    temperature: number;
    throttling: boolean;
    zones: Record<string, number>;
  };
  zram: {
    size: number;
    used: number;
    algorithm: string;
  };
}

export interface ConfigValue {
  key: string;
  value: string;
  description?: string;
}

export interface BusyBoxStatus {
  installed: boolean;
  location: string;
  version: string;
  type: 'builtin' | 'brutal' | 'none';
}

/**
 * Parse configuration file content
 */
export function parseConfigContent(content: string): ConfigValue[] {
  const lines = content.split('\n');
  const config: ConfigValue[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const [key, value] = trimmed.split('=');
    if (key && value !== undefined) {
      config.push({
        key: key.trim(),
        value: value.trim(),
      });
    }
  }

  return config;
}

/**
 * Generate updated configuration content
 */
export function generateConfigContent(config: ConfigValue[]): string {
  let content = '# Lynx Configuration\n';
  content += '# Auto-generated by WebUI\n\n';

  for (const item of config) {
    content += `${item.key}=${item.value}\n`;
  }

  return content;
}

/**
 * Validate configuration value
 */
export function validateConfigValue(key: string, value: string): { valid: boolean; error?: string } {
  // Validate known configuration keys
  const validKeys: Record<string, { type: string; pattern?: RegExp }> = {
    'lynx.mode': { type: 'enum', pattern: /^(notset|auto|aggressive|high|powersave)$/ },
    'lynx.thermal': { type: 'enum', pattern: /^(notset|0|1)$/ },
    'lynx.control': { type: 'enum' },
    'lynx.cc': { type: 'number', pattern: /^\d+$/ },
    'lynx.fcc': { type: 'string' },
    'lynx.lcc': { type: 'number', pattern: /^[\d.]+$/ },
    'lynx.ac': { type: 'string' },
    'lynx.max.ac': { type: 'number', pattern: /^\d+$/ },
    'lynx.min.ac': { type: 'number', pattern: /^\d+$/ },
    'lynx.flow': { type: 'enum', pattern: /^(notset|0|1)$/ },
    'flow.mode': { type: 'enum', pattern: /^(notset|0|1|2|3|5)$/ },
    'window': { type: 'string' },
    'trans': { type: 'string' },
    'anim': { type: 'string' },
  };

  if (!validKeys[key]) {
    return { valid: false, error: `Unknown configuration key: ${key}` };
  }

  const keyConfig = validKeys[key];
  if (keyConfig.pattern && !keyConfig.pattern.test(value)) {
    return { valid: false, error: `Invalid value for ${key}: ${value}` };
  }

  return { valid: true };
}

/**
 * Build performance mode configuration
 */
export function buildPerformanceModeConfig(mode: 'auto' | 'aggressive' | 'high' | 'powersave'): ConfigValue[] {
  const modeConfig: Record<string, ConfigValue[]> = {
    auto: [
      { key: 'lynx.mode', value: 'auto' },
    ],
    aggressive: [
      { key: 'lynx.mode', value: 'aggressive' },
    ],
    high: [
      { key: 'lynx.mode', value: 'high' },
    ],
    powersave: [
      { key: 'lynx.mode', value: 'powersave' },
    ],
  };

  return modeConfig[mode] || [];
}

/**
 * Build ZRAM configuration
 */
export function buildZramConfig(size: string): ConfigValue[] {
  return [
    { key: 'zram.size', value: size },
  ];
}

/**
 * Build thermal configuration
 */
export function buildThermalConfig(enabled: boolean): ConfigValue[] {
  return [
    { key: 'lynx.thermal', value: enabled ? '1' : '0' },
  ];
}

/**
 * Parse Lxcore command output
 */
export function parseLxcoreOutput(output: string): { success: boolean; message: string } {
  const lines = output.split('\n');
  let success = true;
  let message = '';

  for (const line of lines) {
    if (line.includes('Error') || line.includes('error') || line.includes('❌')) {
      success = false;
    }
    if (line.includes('✅') || line.includes('Success')) {
      success = true;
    }
    message += line + '\n';
  }

  return { success, message: message.trim() };
}

/**
 * Generate Lxcore command for performance mode
 */
export function generateLxcoreCommand(mode: 'auto' | 'aggressive' | 'high' | 'powersave'): string[] {
  const commands: Record<string, string[]> = {
    auto: ['Lxcore -cpu apply', 'Lxcore -gpu apply', 'Lxcore -ram apply'],
    aggressive: ['Lxcore -cpu apply', 'Lxcore -gpu apply', 'Lxcore -ram apply'],
    high: ['Lxcore -cpu apply', 'Lxcore -gpu apply', 'Lxcore -ram apply'],
    powersave: ['Lxcore -cpu apply', 'Lxcore -gpu apply', 'Lxcore -ram apply'],
  };

  return commands[mode] || [];
}

/**
 * Generate Lxcore command for ZRAM
 */
export function generateZramCommand(size: string): string {
  return `Lxcore -zram set size=${size}`;
}

/**
 * Generate Lxcore command for thermal
 */
export function generateThermalCommand(enabled: boolean): string[] {
  const commands: string[] = [];
  
  if (enabled) {
    commands.push('cmd thermalservice override-status 0');
  }

  return commands;
}

/**
 * Parse system metrics from /proc files
 */
export function parseSystemMetrics(procData: Record<string, string>): SystemMetrics {
  const metrics: SystemMetrics = {
    cpu: {
      usage: 0,
      cores: 0,
      frequency: [],
      governors: [],
    },
    gpu: {
      frequency: '0',
      load: 0,
    },
    ram: {
      total: 0,
      available: 0,
      used: 0,
      percentage: 0,
    },
    thermal: {
      temperature: 0,
      throttling: false,
      zones: {},
    },
    zram: {
      size: 0,
      used: 0,
      algorithm: 'lz4',
    },
  };

  // Parse CPU info
  if (procData.cpuinfo) {
    metrics.cpu.cores = (procData.cpuinfo.match(/processor/g) || []).length;
  }

  // Parse CPU frequency
  if (procData.cpuFreq) {
    metrics.cpu.frequency = [String(parseInt(procData.cpuFreq) / 1000)];
  }

  // Parse CPU governor
  if (procData.cpuGov) {
    metrics.cpu.governors = [procData.cpuGov.trim()];
  }

  // Parse RAM metrics
  if (procData.meminfo) {
    const memLines = procData.meminfo.split('\n');
    for (const line of memLines) {
      if (line.startsWith('MemTotal:')) {
        metrics.ram.total = parseInt(line.split(/\s+/)[1]) * 1024;
      }
      if (line.startsWith('MemAvailable:')) {
        metrics.ram.available = parseInt(line.split(/\s+/)[1]) * 1024;
      }
    }
    metrics.ram.used = metrics.ram.total - metrics.ram.available;
    metrics.ram.percentage = (metrics.ram.used / metrics.ram.total) * 100;
  }

  // Parse thermal metrics
  if (procData.thermal) {
    metrics.thermal.temperature = parseInt(procData.thermal) / 1000;
  }

  // Parse ZRAM metrics
  if (procData.zramSize) {
    metrics.zram.size = parseInt(procData.zramSize);
  }

  if (procData.zramStat) {
    const stats = procData.zramStat.split(/\s+/);
    metrics.zram.used = parseInt(stats[2]) || 0;
  }

  return metrics;
}

/**
 * Generate BusyBox installation script
 */
export function generateBusyBoxInstallScript(): string {
  return `#!/bin/sh
MODPATH="/data/adb/modules/Lynx"
mkdir -p $MODPATH/system/xbin

# Try KSU built-in
if [ -f /data/adb/ksu/bin/busybox ]; then
  cp -f /data/adb/ksu/bin/busybox $MODPATH/system/xbin/busybox
  chmod 755 $MODPATH/system/xbin/busybox
  chown 0:0 $MODPATH/system/xbin/busybox
  $MODPATH/system/xbin/busybox --install -s $MODPATH/system/xbin/
  echo "BusyBox installed from KSU"
  exit 0
fi

# Try Magisk built-in
if [ -f /data/adb/magisk/busybox ]; then
  cp -f /data/adb/magisk/busybox $MODPATH/system/xbin/busybox
  chmod 755 $MODPATH/system/xbin/busybox
  chown 0:0 $MODPATH/system/xbin/busybox
  $MODPATH/system/xbin/busybox --install -s $MODPATH/system/xbin/
  echo "BusyBox installed from Magisk"
  exit 0
fi

echo "Failed to locate BusyBox"
exit 1
`;
}

/**
 * Parse module information from module.prop
 */
export function parseModuleInfo(content: string): Record<string, string> {
  const lines = content.split('\n');
  const info: Record<string, string> = {};

  for (const line of lines) {
    const [key, value] = line.split('=');
    if (key && value) {
      info[key.trim()] = value.trim();
    }
  }

  return info;
}

/**
 * Format device information for display
 */
export function formatDeviceInfo(props: Record<string, string>): Record<string, string> {
  return {
    brand: props['ro.product.system.brand'] || 'Unknown',
    model: props['ro.product.system.model'] || 'Unknown',
    processor: props['ro.product.board'] || 'Unknown',
    android: props['ro.system.build.version.release'] || 'Unknown',
    sdk: props['ro.build.version.sdk'] || 'Unknown',
    architecture: props['ro.product.cpu.abi'] || 'Unknown',
    kernel: props['kernel.version'] || 'Unknown',
  };
}
